### ISSUE TITLE
Calendar doesn't render properly in a built svelte app

### ISSUE THREAD

**Issue by sridharraman** [6eDesign/svelte-calendar#124]
When I do a `npm run build` and run the built app, the calendar component doesn't load properly. There's a huge gap in the div after the button. The button is not clickable as well. I wonder if I am doing something wrong. The build is done through rollup.

Edit: The calendar works absolutely fine in dev environment.

**Comment by 6eDesign** [comment]
Please provide a clear way to reproduce the issue you're seeing.  There are many ways to build/run/develop a svelte application and there are various versions of dependencies (svelte-calendar and otherwise).  I have not experienced the issue you're describing when implementing this calendar in svelte applications (neither in development or production builds).
