### ISSUE TITLE
Feature: How to internationalize the calendar

### ISSUE THREAD

**Issue by jdgaravito** [6eDesign/svelte-calendar#37]
hi, its me again. i managed to install and make it work. its awesome but now i have a problem. i cant make work the itnernationalization of timeUtilis.
```
<script>  
import { internationalize } from 'timeUtils';
import { formatDate } from 'timeUtils';

internationalize({
  daysOfWeek: [
    'Domingo',
    'Lunes',
    'Martes',
    'Miércoles',
    'Jueves',
    'Viernes',
    'Sábado'
  ],
  monthsOfYear: [
    'Enero',
    'Febrero',
    'Marzo',
    'Abril',
    'Mayo',
    'Junio',
    'Julio',
    'Agosto',
    'Septiembre',
    'Octubre',
    'Noviembre',
    'Diciembre'
  ]
})
</script>
```
it  changes in the chosen date of the button but not in the calendar.
Thank you.

**Comment by jdgaravito** [comment]
Update: i manage to edit the dictionaries.js file to change it manually. and some colors in the styles also. but what if i update the calendar, i will lost the changes. it is posible to make a themed functionality in a near future?

Also another feature suggestion. having a time selector with the same design principle will be great. 

i loved your component. his UX is awesome. keep it up!!

**Comment by 6eDesign** [comment]
Hey @jdgaravito, great question.  Timeutils does support basic internationalization but I haven't tested this in svelte-calendar yet.  I'll do some experimenting and get it working in the near future so you don't have to worry about upgrading the component in the future.

Theming might be slightly complicated but perhaps it's best to make the styles global so you can easily override with your own stylesheet.  I'll look into this as well, thanks for raising this issue.

**Comment by jdgaravito** [comment]
Update: as i expected every time i use npm or yarn the changes made to the the styles and dictionaries get lost 😢 

check this library: (https://github.com/rob-balfre/svelte-select) can be a way to have a styling functionality in the future with css variables on the calendar.

**Comment by 6eDesign** [comment]
@jdgaravito & @pzmarzly (who also has requested this feature) - I have just cut a v1.2.0 which exposes two new props called `daysOfWeek` and `monthsOfYear`.  These allow you to specify the "dictionaries" used by both `svelte-calendar` and `timeUtils` for the purpose of internationalization.  I've added instructions to the readme and here is an example which uses my rusty understanding of the Spanish language: 

```html
<script>
  const daysOfWeek = [
    [ 'Domingo', 'Dom' ],
    [ 'Lunes', 'Lun' ],
    [ 'Martes', 'Mar' ],
    [ 'Miércoles', 'Mié' ],
    [ 'Jueves', 'Jue' ],
    [ 'Viernes', 'Vie' ],
    [ 'Sábado', 'Sáb' ],
  ];
  const monthsOfYear = [
    [ 'Enero', 'Ene' ],
    [ 'Febrero', 'Feb' ],
    [ 'Marzo', 'Mar' ],
    [ 'Abril', 'Abr' ],
    [ 'Mayo', 'May' ],
    [ 'Junio', 'Jun' ],
    [ 'Julio', 'Jul' ],
    [ 'Agosto', 'Ago' ],
    [ 'Septiembre', 'Sep' ],
    [ 'Octubre', 'Oct' ],
    [ 'Noviembre', 'Nov' ],
    [ 'Diciembre', 'Dic' ],
  ];
</script>

<Datepicker
  daysOfWeek={daysOfWeek}
  monthsOfYear={monthsOfYear}
/>
```
I'd appreciate any feedback you may have after giving this a spin.  I think this should work well for any language as long as its days/months can be expressed both in short and long form.  I'll leave this issue open for now in case either of you encounter any issues with this implementation.

**Comment by pzmarzly** [comment]
@6eDesign thanks a lot for this. A minor nitpick (irrelevant to me): in Slavic languages, noun forms change (due to case forms). Thus, e.g. in Polish "February 2020" is "luty 2020", but "2. February 2020" (second **of** February 2020) is "2. lut**ego** 2020". Hence, I cannot use `#{F}` (full month) formatting option, as it would give "2. luty 2020" (otherwise I would have incorrect headers in the calendar popup). But I prefer `#{M}` (short month) anyway, where this problem doesn't occur. Actually a lot of programs use short month names, probably to avoid this i18n mess.

Then again, it's a minor issue, and even if I used full month names, such grammar mistakes wouldn't prevent anyone from understanding the date (it would just sound wrong in their heads). There are lot of programs that make such mistakes, and almost no one cares.

Weeks not starting on Monday would be a much more distracting problem for users, though.

**Comment by 6eDesign** [comment]
Thanks for the feedback @pzmarzly.  I'm not sure we can accommodate the complexities of every language here but I'm hoping that this change, in addition to the ability to pass the `format` prop as a function, will largely fill the internationalization gap that this component had previously.   With that said, I'm definitely not well-versed in this subject matter and would not be terribly surprised if this topic pops up again in the future.

**Comment by jdgaravito** [comment]
thank you so much!1 i will try and tell you.

**Comment by daliusd** [comment]
I have tested this one as well. It works well but one more change is required. In my project I allow to change language real-time without refreshing website. That means Datepicker is not respecting `daysOfWeek` change because there is some initialization code on creation but not on update. I believe `monthsOfYear` 

E.g. sortedDaysOfWeek could be changed to this in Datepicker.svelte:
```
       let sortedDaysOfWeek;
    $: {
        internationalize({ daysOfWeek, monthsOfYear });
        sortedDaysOfWeek =
            weekStart === 0
                ? daysOfWeek
                : (() => {
                      let dow = daysOfWeek.slice();
                      dow.push(dow.shift());
                      return dow;
                  })();
    }

```

**Comment by pzmarzly** [comment]
43de4fea3bd9d593cd5ffd6856a202d03e5bbb88 added `weekStart` parameter. Thanks a lot for that.

`<Datepicker weekStart=1 />` does not seem to work (due to type mismatch in `date.getDay() !== weekStart`). `<Datepicker weekStart={1} />` works, but I'm not sure whether it is the way that parameter was meant to be supplied. I don't mind if it was, though.

**Comment by 6eDesign** [comment]
> [43de4fe](https://github.com/6eDesign/svelte-calendar/commit/43de4fea3bd9d593cd5ffd6856a202d03e5bbb88) added `weekStart` parameter. Thanks a lot for that.
> 
> `<Datepicker weekStart=1 />` does not seem to work (due to type mismatch in `date.getDay() !== weekStart`). `<Datepicker weekStart={1} />` works, but I'm not sure whether it is the way that parameter was meant to be supplied. I don't mind if it was, though.

No need to thank me, someone else contributed that bit (I firmly believe weeks start on Sunday ;) jk).  We could loosen the equality check here but the idea was, indeed, to use `weekStart={variableOrInteger}`.

**Comment by antony** [comment]
It's worth noting that there is an open RFC on Svelte for styling components. It might be worth deferring styling until this is fleshed out / done.

**Comment by 6eDesign** [comment]
@antony I actually added some styling capabilities a while back (see readme for details), but I'm curious about the RFC you mentioned, do you have a link?

**Comment by nickolasgregory** [comment]
This one I think: https://github.com/sveltejs/rfcs/pull/13

**Comment by julien-vu** [comment]
A question : how do you use the format ? cant find any example with : 
- the svelte basic implementation
- a function to format (in Japan it's yyyy-mm-dd)

**Comment by 6eDesign** [comment]
Internationalization has been overhauled in v3.  See the locale example here https://6edesign.github.io/svelte-calendar/docs/examples 

Please feel free to reopen or submit a new issue if you continue to have trouble
