### ISSUE TITLE
Feature: Allow to embed inline

### ISSUE THREAD

**Issue by rottmann** [6eDesign/svelte-calendar#52]
without click a button to open.

**Comment by 6eDesign** [comment]
Hey @rottmann could you explain what you're looking for in a little more detail?  Do you want the calendar to be "always open" (even after a date is selected) or are you looking for a non-button trigger that opens the calendar (such as a link or text node)?

**Comment by rottmann** [comment]
I need a permanent visible calender within the page (not as popover).

**Comment by artur-sim** [comment]
> Hey @rottmann could you explain what you're looking for in a little more detail? Do you want the calendar to be "always open" (even after a date is selected) or are you looking for a non-button trigger that opens the calendar (such as a link or text node)?

I was actually also looking for option you described. How to show calendar without button ?

**Comment by antony** [comment]
@artur-sim @rottmann right now you can't do this. However I think this is a good first PR, since it would essentially involve extracting the calendar from the trigger, and placing it into a new top-level component.

Then, the parent component would render (probably using `<svelte:component>`) the popout one, or the embedded one, depending on user preference.

**Comment by tonprince** [comment]
Is there any solution for that in the meantime?

**Comment by 6eDesign** [comment]
An InlineCalendar component has been added in v3 of this component.  Please refer to the new docs https://6edesign.github.io/svelte-calendar/
