### ISSUE TITLE
error on client / server : Could not find owner for node

### ISSUE THREAD

**Issue by jdgaravito** [6eDesign/svelte-calendar#75]
Hi, I love your calendar. Started a project and imported the component:

but as soon i use any of the examples i get:
```
✔ service worker (352ms)
✗ client
Could not find owner for node
✗ server
Could not find owner for node
✔ service worker (237ms)
```

i'm just using:

```
<script>
import Datepicker from "svelte-calendar";
//calendar variables
  let formattedSelected;
  let dateChosen;
</script>


<Datepicker
            format="#{l},"
            #{F}
            #{j},
            #{Y}
            bind:formattedSelected
            bind:dateChosen>
            <button class="custom-button">
              {#if dateChosen}Chosen: {formattedSelected}{:else}Pick a date{/if}
            </button>
          </Datepicker>
```

any idea why this happen?

**Comment by jdgaravito** [comment]
it has to do with the format field: format="#{l},"
            #{F}
            #{j},
            #{Y}

should i isntall timeutils?

**Comment by 6eDesign** [comment]
Hey @jdgaravito - you don't need to install timeUtils.  You can fix this by defining the `format` prop value in the script section instead of in the HTML.  Here's an example: https://svelte.dev/repl/067992cf15314ddea004038fc2375aed?version=3.19.2

This happens because svelte will attempt to replace values within `{}`'s when they are present in the markup and timeUtils also uses `{}'s for its string templating.   Closing this for now but feel free to revive/comment if you're still having difficulties.

**Comment by jdgaravito** [comment]
thank you so much!! i really appreciate the time you take to answer. this is the best svelte component i ever used. keep it up
